AllCops:
  TargetRubyVersion: 2.1

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# We do not actually need Rails checks except Rails/Output, but in order to
# make it run we have to enable the whole suite.
Rails:
  Enabled: true

Rails/Output:
  Enabled: true
  Details: "\nActually, do not do console logging at all in the gem."
